In [5]:
import numpy as np

In [7]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [8]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [9]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [10]:
revenue - expenses

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [11]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [14]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

In [16]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
70*matrix

array([[ 70, 140, 210],
       [280, 350, 420],
       [490, 560, 630]])

In [24]:
np.dot(70, matrix)

array([[ 70, 140, 210],
       [280, 350, 420],
       [490, 560, 630]])